Added better debugging.

diff --git a/gpack b/gpack
--- a/gpack
+++ b/gpack
@@ -27,7 +27,10 @@
 ########################################################################
 
 #later on in Sat system this will be in absolute dir
-. ./gpackint.sh
+if ! . ./gpackint.sh ; then
+    echo "Could not find GPack function library. Check GPack setup."
+    exit 1
+fi
 
 # set up package list (for multiple install/removes etc.)
 PKGS=(`echo $@`)
